--- 

- name: Deploy web and database 
  become: yes 
  become_user: root 
  hosts: all 

  roles: 
    role: webserver
    vars: 
      apache_port: 8080

    role: database

    
# to execute the play book execute the command - ansible-playbook site.yaml -i inventory 

 