apiVersion: apps/v1
kind: ReplicaSet 
metadata:
  name:
  value:
spec:
  replicas: 3
  selector:
    matchlabels: 
      app: nginx
  template: 
    metadata: 
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports: 
        - containerPort: 80


