- name: Create a new user
  hosts: all  # Runs on all servers
  become: yes  # Executes as root
  
  tasks:
    - name: Create user 'devops'
      user:
        name: devops
        state: present
        shell: /bin/bash
