# write 5 Ansible playbooks

#1. Install a package ( apt module ) You are setting up a web server and need to install Nginx as the primary web server. This will ensure that the package is installed on all the servers in the web_server group.

- name: Install nginx on ubuntu server
  hosts: web_servers
  become: yes
  become_user: root 

  tasks: 
    - name: install nginx
      apt:
        name: nginx
        state: present 
     
     
 #2. start and enable a service ( service module )
 
 - name: 
 
 
  
   
  
  
   
   
  
 